### ISSUE TITLE
spam message

### ISSUE THREAD

**Issue by jumpjack** [ehn-dcc-development/hcert-spec#106]
Someone claims the keys are not stolen. Run this then...

HC1:NCFOXN%TSMAHN-H/RCMPQ5GE5I00H9GBH3QNAD6.LQLX85ZS GJTSJ4NKP1HCV4*XUA2PSGH.+H$NI4L6F$S-N1FYBRR1$Q1+GOF+P$HQPHQHTQ.SQ6$PUKRN95404.W7UX4795L*KDYPWGO+9AZDOHCRL35IWMSDOP7OQ+M70AK$8 96XY4SBLU96:/6N9R%EPL8RY9DOA60-K.IA.C8KRDL4O54O4IGUJKJGI0JAXD15IAXMFU*GSHGRKMXGG6DBYCBMQN:HG5PAHGG8KES/F-1JW-K%B3A9ENO4B-S-*O4-G1FD/U47HAE1MI4OE0G1:HHD4AB874MM-6B:HKJSQ.TAG3CR1638W9AV88G64PB4VHRY2EK03NFJL4M10KP3AT2VK LT5GGFV85I0*10W2ZXJSBTMFW*+KM2T8-CXR32BMF7RAEAYKMWHE/NH UP4SNGENEWUY97 -3YM0.HAM:D:00ZY35XRT1100MFKWEWYHKCZIZJ0CAQYIKOZIZJ0DAQCDQGAE62ORR7HL0POYQCGMGBBEQFCBCDCT4VYFQZEPYFXK69ZRV9T8IY6NWAYEJF0VXVKNFCG/X9UIG5HFWRPEDW2EPW00S1K83I3900:919FUCKYOUALLGPSUPPORTERS9IKM24N21AW7ZUR2L013300EUISGOEINGDOWNNAZZYFUCKERS666I3AK96XYR01300STOREMYCODEMUTHERFUCKERANDGOTOHELLI5340XRT09SHUZVB33IR0IPUTAVIRUSHERE83H73KFI280I23KL0YRZT91Y0WITHLOVEFROMHA1*PWEOXCI/QXRLOZKN0LM*03I2RWT0Z

_Originally posted by @Maxmontgelas in https://github.com/ehn-dcc-development/hcert-spec/discussions/105#discussioncomment-1573490_

**Comment by 0ki** [comment]
This is visibly not base45. :)

**Comment by Maxmontgelas** [comment]
And yet it passes, so your smiles are for?

**Comment by Maxmontgelas** [comment]
It is categorically not spam. and should be adressed too. it passes the verification.

**Comment by jumpjack** [comment]
How can it pass any verification a BASE45 string containing these data?

7HL0POYQCGMGBBEQFCBCDCT4VYFQZEPYFXK69ZRV9T8IY6NWAYEJF0VXVKNFCG/X9UIG5HFWRPEDW2EPW00S1K83I3900:919**FUCK YOU ALL GP SUPPORTERS**9IKM24N21AW7ZUR2L013300**EU IS GOEING DOWN NAZZY FUCKERS 666**I3AK96XYR01300**STORE MY CODE MUTHER FUCKER AND GO TO HELL**I5340XRT09SHUZVB33IR0IPUTAVIRUSHERE83H73KFI280I23KL0YRZT91Y0**WITH LOVE FROM HA**1PWEOXCI/QXRLOZKN0LM03I2RWT0Z

**Comment by jumpjack** [comment]
It looks like this user is trying to mess things up and crack the system, is it possibile to ban it from this repository?

He even forked the GP issuance server, probably hoping to be able to use it to create its own GPs...

![image](https://user-images.githubusercontent.com/1620953/139843052-2e007fc5-8387-4091-8568-6a4ccca11dba.png)

**Comment by jschlyter** [comment]
@jumpjack forking a public repo isn't really that uncommon.
@Maxmontgelas please stay in line or you will be blocked.

**Comment by Maxmontgelas** [comment]
https://ibb.co/Bc8rFW1 I already posted the QR code result.

**Comment by Maxmontgelas** [comment]
> @jumpjack forking a public repo isn't really that uncommon. @Maxmontgelas please stay in line or you will be blocked.

Forking is usual to understand how things work to find flaws and then to contribute back. I did not create that String, I copy pasted from elsewhere, It was very late at night and my mistake I had not read every part of it, so i apologise for that as was not aware of the profanities at that time. as you can see, there is an obvious flaw here https://ibb.co/Bc8rFW1 and one that can be messed with much further. I am discussing everything else that I found last night in private now and that is why I am not elaborating on here on what i actually found since have ben contacted privately and think it is the best corse to keep it private for now.

**Comment by jschlyter** [comment]
noted @Maxmontgelas
