### ISSUE TITLE
iPhone Camera App adds unexpected %20 encoding

### ISSUE THREAD

**Issue by thinkberg** [ehn-dcc-development/hcert-spec#72]
I found an annoying issue with the Base45 encoding. Scanned with the iPhone Camera App and selecting the unusable data to copy copies the data, but encodes all Spaces as %20 for some reason. I checked the actual bytes in the QR Code and they are spaces.

**Comment by jschlyter** [comment]
see also #64

**Comment by jschlyter** [comment]
We are aware this issue and other issues with `HC1` encoding. Many camera apps assume that scanned payloads are URIs, and `HC1` payload is not.
